services:
  devcontainer:
    image: env-decorators-dev-container
    container_name: env-decorators-dev-container
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    runtime: runsc
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - ../:/workspace:cached
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2gb