services:
  devcontainer:
    image: environments-resolve-dev-container
    container_name: environments-resolve-dev-container
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    runtime: runsc
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached