name: Node CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Cache preparing per os
  prepare-npm-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    with: {os: ubuntu-latest}

  prepare-npm-cache-macos:
    uses: ./.github/workflows/prepare-cache.yml
    with: {os: macos-latest}

  prepare-npm-cache-windows:
    uses: ./.github/workflows/prepare-cache.yml
    with: {os: windows-latest}

  # Unit testing per os
  test-ubuntu:
    name: Testing on ubuntu
    needs: prepare-npm-cache-ubuntu

    uses: ./.github/workflows/test.yml
    with: {os: ubuntu-latest}

  test-macos:
    name: Testing on macos
    needs: prepare-npm-cache-macos

    uses: ./.github/workflows/test.yml
    with: {os: macos-latest}

  test-windows:
    name: Testing on windows
    needs: prepare-npm-cache-windows

    uses: ./.github/workflows/test.yml
    with: {os: windows-latest}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare-npm-cache-ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: install packages
        run: npm install --ignore-scripts

      - name: run eslint
        run: npm run lint
