name: Prepare CI cache

on:
  workflow_call:
    inputs:
      os: {required: true, type: string}

jobs:
  prepare-npm-cache:
    name: Prepare cache job
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: install packages
        run: npm install --ignore-scripts
