name: Testing

on:
  workflow_call:
    inputs:
      os: { required: true, type: string }

jobs:
  test:
    name: Node v${{ matrix.node-version }}
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: npm run test